### ISSUE TITLE
Asuswrt could not work correct with HA 108.9

### ISSUE THREAD

**Issue by plutosherry** [kennedyshead/aioasuswrt#38]
## Environment

- Home Assistant Core release with the issue:  asuswrt
- Last working Home Assistant Core release (if known):  107.3
- Operating environment (Home Assistant/Supervised/Docker/venv):  Docker
- Integration causing this issue:  no
- Link to integration documentation on our website:  

## Problem-relevant `configuration.yaml`

```yaml
asuswrt:
  host: 192.168.1.1
  username: admin
  ssh_key: /config/ssh/asuswrt-rsa-key
  protocol: ssh
  port: 22
  interface: br0
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed
```

## Traceback/Error logs

```txt
Logger: homeassistant.setup
Source: components/asuswrt/__init__.py:81
First occurred: 下午9:06:48 (1 occurrences)
Last logged: 下午9:06:48

Error during setup of component asuswrt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/usr/src/homeassistant/homeassistant/components/asuswrt/__init__.py", line 81, in async_setup
    dnsmasq=conf[CONF_DNSMASQ],
TypeError: __init__() got an unexpected keyword argument 'interface'
```

## Additional information

That's it
PLZ help me ..... thx!!!

**Comment by bskaplou** [comment]
Remove line "interface: br0" from config
