### ISSUE TITLE
Error on SSH connection

### ISSUE THREAD

**Issue by GoNzCiD** [kennedyshead/aioasuswrt#40]
Hi, I've tested with an Asus AC87U with merlin firmware version 384.13_10. 
* This component worked sometime ago.
* The error is: **[Errno 104] Connection reset by peer**
* The code for the example:
  ```python
  import asyncio
  import logging
  import sys
  from aioasuswrt.asuswrt import AsusWrt
  
  component = AsusWrt('192.168.1.1', 22, username='USER', password='PASS')
  logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
  logger = logging.getLogger(__name__)
  
  async def print_data():
      logger.debug(await component.connection.async_connect())  
  
  loop = asyncio.get_event_loop()
  loop.run_until_complete(print_data())
  loop.close()
  ```
* Trace:
  ```log
  DEBUG:asyncio:Using selector: EpollSelector
  Traceback (most recent call last):
    File "asus.py", line 18, in <module>
      loop.run_until_complete(print_data())
    File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
      return future.result()
    File "asus.py", line 14, in print_data
      logger.debug(await component.connection.async_connect())
    File "/usr/local/lib/python3.7/site-packages/aioasuswrt/connection.py", line 75, in async_connect
      self._client = await asyncssh.connect(self._host, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/asyncssh/connection.py", line 5696, in connect
      conn_factory, 'Opening SSH connection to')
    File "/usr/local/lib/python3.7/site-packages/asyncssh/connection.py", line 175, in _connect
      await conn.wait_established()
    File "/usr/local/lib/python3.7/site-packages/asyncssh/connection.py", line 1927, in wait_established
      await self._waiter
    File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 814, in _read_ready__data_received
      data = self._sock.recv(self.max_size)
  ConnectionResetError: [Errno 104] Connection reset by peer
  ```

Thanks

**Comment by GoNzCiD** [comment]
Downloading the code and with latest dependencies it works.
I think it had stopping working since last firmware updrade that suprime older ciphers.

It should be possible to generate a new version with the dependencies updated? Thanks
