### ISSUE TITLE
await_get_nvram_info

### ISSUE THREAD

**Issue by lb3ne** [kennedyshead/aioasuswrt#76]
Got sent here, with my issue, due to integration using this?!

I got the following in my log, on every boot of HA:

Logger: homeassistant.config_entries
Source: components/asuswrt/router.py:426
First occurred: 5. juni 2021, 19:01:03 (1 occurrences)
Last logged: 5. juni 2021, 19:01:03

Error setting up entry 192.168.0.1 for asuswrt
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/asuswrt/init.py", line 123, in async_setup_entry
await router.setup()
File "/usr/src/homeassistant/homeassistant/components/asuswrt/router.py", line 230, in setup
model = await _get_nvram_info(self._api, "MODEL")
File "/usr/src/homeassistant/homeassistant/components/asuswrt/router.py", line 426, in _get_nvram_info
info = await api.async_get_nvram(info_type)
File "/usr/local/lib/python3.8/site-packages/aioasuswrt/asuswrt.py", line 275, in async_get_nvram
lines = await self.connection.async_run_command(_NVRAM_CMD)
File "/usr/local/lib/python3.8/site-packages/aioasuswrt/connection.py", line 140, in async_run_command
return [line.decode("utf-8") for line in data]
File "/usr/local/lib/python3.8/site-packages/aioasuswrt/connection.py", line 140, in 
return [line.decode("utf-8") for line in data]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 4: invalid start byte

Tell me if you need more then this log, and I will find.

The router is anyways a RT-N66W, and is not updated for the last months, and there isn't any available updates for it.

Anyway, this issue started with HA 2021.6.

**Comment by lb3ne** [comment]
https://github.com/home-assistant/core/issues/51498

Was referred to here, from the issue over.
